apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      name: eureka-server
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: mavavericks/eureka-server:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8671
              protocol: TCP
      restartPolicy: Always


---

apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  selector:
    app: eureka-server
  ports:
    - protocol: TCP
      port: 8671
      targetPort: 8671
  type: NodePort
    
      
